apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: journal-club-bot
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/journal-club-bot:latest
        ports:
        - containerPort: 8080
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: JC_TIMEZONE
          value: "America/Los_Angeles"
        - name: JC_SOURCE_LABEL
          value: "buffer-label"
        - name: JC_PROCESSED_LABEL
          value: "jc-processed"
        - name: JC_CAL_PREFIX
          value: "Journal Club – "
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
